# Site settings
title: Triple Equal Software
description: 'Triple Equal Software - We Build Apps'
url: 'http://tripleequal.net'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Bob Hanson'
  email: bob@tripleequal.net
  twitter_username: 3equal
  facebook_username: sngndncmn
  github_username:  tripleequal
  linkedin_username:  tripleequal

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
