# Site settings
title: Bob Hanson - Software Engineer
description: "I love the web!"
baseurl: "/space-jekyll-template" # the subpath of your site, e.g. /blog
url: "http://tripleequal.github.io"

# User settings
username: tripleequal
user_title: Bob Hanson - Owner
email: bob@tripleequal.net
twitter_username: tripleequal
github_username:  tripleequal
# gplus_username:  loremipsum
# disqus_username: loremipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: About me
    url: /about
# projects in header index
projects:
  - name: asciilang
    url: https://github.com/victorvoid/asciilang
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
